name: tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches-ignore:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PHPCS in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace bratikov/php:8.3-fpm-alpine-phalcon5.8 sh -c "
          git config --global --add safe.directory /workspace
          composer --working-dir=app --optimize-autoloader install
          cf=\$(git diff-tree --diff-filter=ACM --no-commit-id --name-only -r ${{ github.sha }} | grep -E 'app/.*\.php$' || true)
          echo \$cf
          if [ -z \"\$cf\" ]; then echo \"No PHP files changed\"; echo \"[]\" > /workspace/phpcs.json; exit 0; fi
          php -dmemory_limit=-1 app/vendor/bin/php-cs-fixer fix --dry-run --config app/config/csfixer.php --using-cache=no --path-mode=intersection --show-progress=none --no-interaction --format gitlab \$(git diff-tree --diff-filter=ACM --no-commit-id --name-only -r ${{ github.sha }}) > /workspace/phpcs.json 2>/dev/null
          "
      - name: Upload PHPCS results
        uses: actions/upload-artifact@v4
        with:
          name: phpcs.json
          path: phpcs.json
  
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PHPStan in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace bratikov/php:8.3-fpm-alpine-phalcon5.8 sh -c "
          echo 'Starting Docker container...'
          git config --global --add safe.directory /workspace
          echo 'Configured git safe directory.'
          composer --working-dir=app --optimize-autoloader install
          echo 'Installed Composer dependencies.'
          cp app/config/sample.app.json app/config/local.app.json
          sed -i 's/##[^#]*##//g' app/config/local.app.json
          echo 'Copied and modified configuration.'
          git diff-tree --diff-filter=ACM --no-commit-id --name-only -r ${{github.sha}}
          cf=\$(git diff-tree --diff-filter=ACM --no-commit-id --name-only -r ${{ github.sha }} | grep -E 'app/.*\.php$' || true)
          echo 'Changed files: ' \$cf
          if [ -z \"\$cf\" ]; then echo 'No PHP files changed'; echo '[]' > /workspace/phpstan.json; exit 0; fi
          php -dmemory_limit=-1 app/vendor/bin/phpstan analyze --configuration app/config/phpstan.neon --error-format=gitlab --no-progress \$(git diff-tree --diff-filter=ACM --no-commit-id --name-only -r ${{ github.sha }}) > /workspace/phpstan.json 2>/dev/null
          echo 'PHPStan analysis complete.'
          "
      - name: Upload PHPStan results
        uses: actions/upload-artifact@v4
        with:
          name: phpstan.json
          path: phpstan.json
  
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PHPUnit in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace bratikov/php:8.3-fpm-alpine-phalcon5.8 sh -c "
          composer --working-dir=app --optimize-autoloader install
          cp app/config/sample.app.json app/config/local.app.json
          sed -i 's/##[^#]*##//g' app/config/local.app.json
          php app/vendor/bin/phpunit --configuration app/tests/phpunit.xml --do-not-cache-result
          "