<?php

namespace App\Models;

/**
 * Dummy.
 *
 * @autogenerated by Phalcon Developer Tools
 * @date 2024-11-26, 18:06:58
 *
 * @OA\Schema(
 *     type="object",
 *     title="Dummy response model"
 * )
 */
class Dummy extends Base
{
	/**
	 * @var int
	 * @Primary
	 * @Identity
	 * @Column(column="id", type="integer", nullable=false)
	 * @OA\Property(format="int64", example=1)
	 */
	protected $id;

	/**
	 * @var string
	 * @Column(column="name", type="string", length=255, nullable=false)
	 * @OA\Property(format="string", example="Basic")
	 */
	protected $name;

	/**
	 * @var string
	 * @Column(column="updated_at", type="string", nullable=false)
	 * @OA\Property(format="DateTime", example="2020-09-08 20:00:00")
	 */
	protected $updatedAt;

	/**
	 * @var string
	 * @Column(column="created_at", type="string", nullable=false)
	 * @OA\Property(format="DateTime", example="2020-09-08 20:00:00")
	 */
	protected $createdAt;

	/**
	 * Method to set the value of field id.
	 *
	 * @param  int   $id
	 * @return $this
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Method to set the value of field name.
	 *
	 * @param  string $name
	 * @return $this
	 */
	public function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * Method to set the value of field updated_at.
	 *
	 * @param  string $updatedAt
	 * @return $this
	 */
	public function setUpdatedAt($updatedAt)
	{
		$this->updatedAt = $updatedAt;

		return $this;
	}

	/**
	 * Method to set the value of field created_at.
	 *
	 * @param  string $createdAt
	 * @return $this
	 */
	public function setCreatedAt($createdAt)
	{
		$this->createdAt = $createdAt;

		return $this;
	}

	/**
	 * Returns the value of field id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Returns the value of field name.
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Returns the value of field updatedAt.
	 *
	 * @return string
	 */
	public function getUpdatedAt()
	{
		return $this->updatedAt;
	}

	/**
	 * Returns the value of field createdAt.
	 *
	 * @return string
	 */
	public function getCreatedAt()
	{
		return $this->createdAt;
	}

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->setSchema('test');
		$this->setSource('dummy');
	}

	/**
	 * Independent Column Mapping.
	 * Keys are the real names in the table and the values their names in the application.
	 *
	 * @return array
	 */
	public function columnMap()
	{
		return [
			'id' => 'id',
			'name' => 'name',
			'updated_at' => 'updatedAt',
			'created_at' => 'createdAt',
		];
	}
}
